### ISSUE TITLE
Request if there is interest to detach pyiges from vtk

### ISSUE THREAD

**Issue by mikamove** [pyvista/pyiges#28]
Hello,

I'd like to know if You would be interested in decoupling `pyiges` from `vtk` into a pure parsing library?

As there is no other comparable python library for IGES parsing, I think modularity could lead to more people using it, which then could also contribute.

I needed exactly this and already stripped the VTK-part away for me, but if there is interest, I could provide it and help in integrating the pure-parsing code to `pyvista/pyiges`.

**Roadmap**

- [x] increase Test coverage from given example data to 85%, see #30 
- [ ] increase Test coverage with new example data  to 100%, see #31 
- [ ] decouple pure parser as specified in https://github.com/pyvista/pyiges/issues/28#issuecomment-1499524376

**Comment by banesullivan** [comment]
I think it'd be pretty easy to make the PyVista (VTK) dependency soft and raise an `ImportError` when not available. If you've already done this, definitely open a Pull Request, and I bet we could integrate it

**Comment by mikamove** [comment]
Dear Bane,

Thanks for Your reply :)

In my case, the changes are a bit more rigorous. The main aspect is, that I basically removed all `to_vtk`-Methods from all the `Iges`-Classes.

I think that from the perspective of a pure standalone parsing module, it makes sense to just represent the parsed data, while the `to_vtk` should be functionality outside of this module, as it has a sharper context, as would also any other evaluation/transformation functionality.

For the pyiges, the changes would therefore be a bit larger, basically as follows:
- there is a pure parsing module `pyiges_parse` (= `pyvista/pyiges(old)` minus vtk-code),
- there is `pyvista/pyiges(new)` which imports `pyiges_parse` and adds the `to_vtk`-functionality, the easiest way would be IMO by subclassing each `pyiges_parse.Iges`-Subclass to add the proper `to_vtk`-method.

```python
class RationalBSplineCurve(pyiges_parse.RationalBSplineCurve):

    def to_vtk(self, ...):
        ...
```

Do You think this would be too much effort from Your side? I could imagine trying to contribute that and alsocould create a  deeper first sketch of the design changes as a base for discussion, but it would be important to know first, if You are basically interested to go into this direction.

**Comment by banesullivan** [comment]
Simply having a check that raises an `ImportError` when VTK/PyVista is missing would be much simpler and easier to maintain with the exact same effect

I do not think we could buy into splitting this into separate packages -- this would add too much complexity and maintenance burden.

To be clear, I have nothing to do with this repo and simply help maintain many of the "side projects" like this included in the PyVista org -- going to defer to @akaszynski for any final say here


---- 

If I were to decouple the PyVista dependency, I'd implement a decorator for all of the methods that use PyVista to perform a runtime check:

```py
try:
    import pyvista
except:
    pyvista = None

def _check_pyvista(func):
    def wrapper(*args, **kwargs):
        if pyvista is None:
            raise ImportError('Please install PyVista')
        return func(*args, **kwargs)
    return wrapper

...

class IgesStuff:
    ...
    @_check_pyvista  # add this decorator to methods that use pyvista/vtk
    def to_pyvista(self, *args, **kwargs):
```

Then remove PyVista/VTK from the core dependencies and done.

Another approach would be to split these methods into a mixin-class that only gets mixed in if PyVista/VTK is available, but I don't like this approach as it would mean the API itself could dynamically change and lead to unexpected AttributeErrors for users

**Comment by mikamove** [comment]
Thanks, I understand Your concerns. Say, if I'd provide the code work on both sides (I'd again have to double check if the approach fully works out..., yet I only did the simple part), including more Tests to make it trustworthy, such that only the reviewing and the future maintenance were on Your side, would it still be too much work for You?

**Comment by banesullivan** [comment]
That seems reasonable to me if you're up for it!! Let's just keep it all in this repository, though. @akaszynski, any final thoughts?

**Comment by akaszynski** [comment]
Totally fine with that. Please ping me for review. A bit underwater with notifications.

**Comment by mikamove** [comment]
Thank You.

I'd be fine with staying in the repository, but as far as I understand, the independence of `vtk` as a real effort to the world outside `pyvista` would only be accomplished if `pyiges_parse` becomes installable without `vtk`, which is my motivation.

Following my (not very educated) understanding of modules, this would be accomplishable by either splitting `pyiges(old)` in into two modules `pyiges_parse` and `pyiges(new)` or having a single module with a soft dependency on `vtk`.

Both approaches have downsides:
- Single-module approach: The only way I know to implement the soft dependency is by defining `extras_require` in `setup.py` with "plugins" for `nurbs` and `vtk`. To install the "full" `pyiges` via pip one would then need to specify this, like `pip install pyiges[nurbs,vtk]` (or something like `pyiges[full]` joining the two). This would break existing `pip install` scripts.
- two-module-approach: means more code changes in Your history to review. 

Do You find one of these approaches still acceptable, or see a third solution?

**Comment by mikamove** [comment]
Thank You @akaszynski, I'd call back when I added some tests, it might then make sense to merge them independently before carrying out the decoupling.

**Comment by mikamove** [comment]
@akaszynski @banesullivan As suggested, I added #30 to increase the test coverage separately as a pre step of the decoupling, please let me know if You have any critique.
